name: Deploy-flask

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stop old containers
        run: docker-compose down || true

      - name: Build and Run Container
        run: docker-compose up -d --build