name: DevSecOps End to End Pipeline
on: 
  workflow_dispatch:

jobs:
  deploy:
      uses: ./.github/workflows/code-quality.yml
      uses: ./.github/workflows/secret-scan.yml
      uses: ./.github/workflows/dependencies.yml
      uses: ./.github/workflows/docker-lint.yml
