name: docker build and push
on: 
  push:
    brnaches: [main]
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/git-checkout@v4
      - name: login to docker GitHub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUBUSER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build and push to docker GitHub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{vars.DOCKERHUBUSER}} /${{github.GITHUB_SHA}}